from src.tgbot_expenses.dialogs.callbacks import (back, bills,
                                                  bill_for_deleting,
                                                  categories,
                                                  category_limit,
                                                  changing_bill,
                                                  changing_limit,
                                                  confirmation, delete_bill,
                                                  expenses, new_bill,
                                                  settings,
                                                  statistics)
